const CI_COMMIT_REF_NAME: string = "__CI_COMMIT_REF_NAME__";
const CI_COMMIT_SHA: string = "__CI_COMMIT_SHA__";
const CI_COMMIT_SHORT_SHA: string = "__CI_COMMIT_SHORT_SHA__";
const BUCKET_NAME: string = "__BUCKET_NAME__";
const DEPLOYMENT_DATE: string = "__DEPLOYMENT_DATE__";

export {
  CI_COMMIT_REF_NAME,
  CI_COMMIT_SHA,
  CI_COMMIT_SHORT_SHA,
  BUCKET_NAME,
  DEPLOYMENT_DATE,
};
